### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by ETHwsch** [mariodavid/cuba-petclinic-product-customizations#1]
Hi Mario

I loaded the core project, executed "CUBA > Advanced > Install App Component" and the core project compiled successfully. Afterwards I loaded the lancester-pet-clinic and tried to run the project in the IDE. I got the error messages below. Any idea what went wrong? Thenaks for a feedback.
Werner

 
Execution failed for task ':lancasterpetclinic-web:compileJava'.
> Could not resolve all files for configuration ':lancasterpetclinic-web:compileClasspath'.
   > Could not find com.haulmont.sample.petclinic:petclinic-web-themes:2.0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
     Required by:
         project :lancasterpetclinic-web

**Comment by mariodavid** [comment]
Hi,

this is interesting. I had that problem as well in a beginning when I started out with the example. I asked @web-devel from Haulmont as I expected this was related to the latest CUBA studio release that I was running.

Can you double-check that locally your app-component.xml in the petclinic-core project exactly looked like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<app-component xmlns="http://schemas.haulmont.com/cuba/app-component.xsd"
  dependsOn="com.haulmont.cuba, com.haulmont.addon.helium">

  <module name="global" blocks="*">
    <artifact name="petclinic-global" appJar="true"/>

    <property name="cuba.persistenceConfig" value="+com/haulmont/sample/petclinic/persistence.xml"/>
    <property name="cuba.metadataConfig" value="+com/haulmont/sample/petclinic/metadata.xml"/>
    <property name="cuba.viewsConfig" value="+com/haulmont/sample/petclinic/views.xml"/>
  </module>
  <module name="core" dependsOn="global" blocks="core">
    <artifact name="petclinic-core" appJar="true"/>
    <artifact name="petclinic-core" classifier="db" ext="zip" configuration="dbscripts"/>

    <property name="cuba.springContextConfig" value="+com/haulmont/sample/petclinic/spring.xml"/>
    <property name="cuba.mainMessagePack" value="+com.haulmont.sample.petclinic.core"/>
  </module>
  <module name="web" dependsOn="global" blocks="web">
    <artifact name="petclinic-web" appJar="true"/>
    <artifact name="petclinic-web" classifier="web" ext="zip" configuration="webcontent"/>
    <artifact name="petclinic-web" ext="jar" configuration="themes" classifier="themes"/>


    <property name="cuba.springContextConfig"
      value="+com/haulmont/sample/petclinic/web-spring.xml"/>
    <property name="cuba.dispatcherSpringContextConfig"
      value="+com/haulmont/sample/petclinic/web-dispatcher-spring.xml"/>
    <property name="cuba.windowConfig" value="+com/haulmont/sample/petclinic/web-screens.xml"/>
    <property name="cuba.menuConfig" value="+com/haulmont/sample/petclinic/web-menu.xml"/>
    <property name="cuba.permissionConfig"
      value="+com/haulmont/sample/petclinic/web-permissions.xml"/>
    <property name="cuba.mainMessagePack" value="+com.haulmont.sample.petclinic.web"/>
    <property name="cuba.iconsConfig"
      value="+com.haulmont.sample.petclinic.web.screens.visit.VisitTypeIcon"/>
    <property name="cuba.themeConfig"
      value="+/com/haulmont/sample/petclinic/web/helium-theme.properties"/>
  </module>
</app-component>
```

and not contain anything else? I saw that Studio when working in that project updated the file (because of some Studio bug I assume).

Alternatively, you can reset your local git branch via `git reset --hard` and then from the command line run `./gradlew install` (Linux / Mac) or `gradlew.bat install` (Windows). This way you ensure that CUBA Studio is not changing any file under the hood...

Cheers
Mario

**Comment by ETHwsch** [comment]
Should I wait for fix in the project as mentioned above? 
If I follow the instructions I am getting:

pwd
/Users/spadmin/Downloads/cuba-petclinic-product-customizations-master/lancaster-petclinic
spadmins-MBP:lancaster-petclinic spadmin$ 
git reset --hard
fatal: not a git repository (or any of the parent directories): .git
spadmins-MBP:lancaster-petclinic spadmin$ 
./gradlew install
> Task :lancasterpetclinic-web:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lancasterpetclinic-web:compileJava'.
> Could not resolve all files for configuration ':lancasterpetclinic-web:compileClasspath'.
   > Could not find com.haulmont.sample.petclinic:petclinic-web-themes:2.0.1-SNAPSHOT.
     Searched in the following locations:
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - file:/Users/spadmin/.m2/repository/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - https://dl.bintray.com/cuba-platform/main/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/maven-metadata.xml
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.pom
       - https://jcenter.bintray.com/com/haulmont/sample/petclinic/petclinic-web-themes/2.0.1-SNAPSHOT/petclinic-web-themes-2.0.1-SNAPSHOT.jar
     Required by:
         project :lancasterpetclinic-web

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.6.4/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 3s
17 actionable tasks: 6 executed, 11 up-to-date
spadmins-MBP:lancaster-petclinic spadmin$

**Comment by mariodavid** [comment]
hi, please try again. There was indeed a problem that was probably caused by myself in the settings.gradle file.

Now everything should work. You can download the latest changes via `git pull` and then do another `gradlew install` on the core project. 

The git reset you have to perform on the root directory of the project, not on the Lancaster directory.

This is why it shows:

```
pwd
/Users/spadmin/Downloads/cuba-petclinic-product-customizations-master/lancaster-petclinic
spadmins-MBP:lancaster-petclinic spadmin$
git reset --hard
fatal: not a git repository (or any of the parent directories): .git
```

Instead do a `cd /Users/spadmin/Downloads/cuba-petclinic-product-customizations-master`  and then `git reset --hard` and afterwards a `git pull`.

Bye
Mario
